### ISSUE TITLE
Update phpro/grumphp

### ISSUE THREAD

**Issue by LOBsTerr** [openeuropa/code-review#117]
We are currently facing issue https://github.com/phpro/grumphp/issues/487
I have noticed that you have a quite old version of phpro/grumphp do you consider update it at some point ?

**Comment by vever001** [comment]
+1, this would also solve the confusing JSON output we see at the end of every phpcs run.
See https://github.com/phpro/grumphp/pull/687
And close at the same time https://github.com/openeuropa/code-review/pull/105

**Comment by brummbar** [comment]
This is not easy, as grumphp changed a lot during its 0.x stage. We started a 2.x branch where we updated grumphp to latest version, but the changes are deep also inside the grumphp.yml configuration itself. We don't have capacity to update grumphp in the 1.x branch. There was an attempt of the update as contribution on #104 but it resulted difficult. 
If you can contribute the update in the 1.x keeping the compatibility with the current configuration go ahead, it would be very welcome.

**Comment by LOBsTerr** [comment]
@brummbar I would love to help here, but I'm completely out the context  :( I will take a look, what is going on there
So, far I have created a patch based on the latest version of grumphp, which bring the fix for phpro/grumphp#487.
Can you tell what is the current status of 2.x branch ? 
Thanks

**Comment by brummbar** [comment]
The 2.x branch was updated to the latest grumphp version, but makes all the grumphp.yml declaration incompatible with the current ones. So it can be used theoretically, just you need to make sure to update said file (note that we didn't test it in other components).
The 2.x branch is also not released as I want to update the rulesets, at least for libraries.
For 1.x I don't know how much work is to bring the patch of the linked issue 487.
