### ISSUE TITLE
Drop character limit on first line of commit messages

### ISSUE THREAD

**Issue by pfrenssen** [openeuropa/code-review#28]
Currently there is an arbitrary limit of 60 characters placed on the first line of the commit message. Combined with our other rules of prefixing the message with `OPENEUROPA-1234: ` and suffixing with a period this just leaves us with 42 usable characters. This is not enough to provide a clear description on why a certain change was necessary.

I would suggest to abolish the character limit entirely. Conveying clear information in the git history is more important than having nice looking titles in Github.

It also seems this rule has never been intentional but has been inherited from GrumPHP defaults. Our current [list of conventions for commit messages](https://github.com/openeuropa/code-review/blob/master/CONVENTIONS.md#commit-messages) does not mention an arbitrary character limit.

**Comment by pfrenssen** [comment]
Looking at [the code in GrumPHP](https://github.com/phpro/grumphp/blob/master/src/Task/Git/CommitMessage.php) it seems it is not currently possible to disable this check. I made a feature request for this: https://github.com/phpro/grumphp/issues/532

**Comment by ademarco** [comment]
The upstream PR has been merged, we just need to add the following to our code-review standard right?

```
max_subject_width: 0
max_body_width: 0
```

**Comment by ademarco** [comment]
We should actually just remove the patch in composer.json since it has been merged.

**Comment by ademarco** [comment]
Closing as this has been fixed in 1.0.0-alpha2.
