### ISSUE TITLE
Update squizlabs/php_codesniffer to 3.4.1

### ISSUE THREAD

**Issue by voidtek** [openeuropa/code-review#82]
We could update `squizlabs/php_codesniffer` to `3.4.1` and remove the following patch 
`"Fix conflict between scope indentation and array indentation checking. Ref. https://github.com/squizlabs/PHP_CodeSniffer/issues/2281": "https://gist.githubusercontent.com/drupol/c307b48fe4eb187b0833afb1d1b97e6a/raw/c3d414e9f4c182387ca9405c36f5daeb7b51ae05/phpcs-390bffe2265aac8184fdf86400c0d0841e65bc4b.patch"`

**Comment by dxvargas** [comment]
Fixed in https://github.com/openeuropa/code-review/pull/85
